server:
  port: 8888
  servlet:
    context-path: /yml

name: "b\nt"

person:
  id: 111
  age: 222
  name: bytetube_${person.dog.age}
  nick-names:
    - byte
    - tube
    - bt
  dog:
    age: 20
    name: larry
  dogs:
    - age: 11
      name: abc_${person.dog.name}
    - age: 22
      name: def_${server.port}