spring:
  profiles:
    active: development
server:
  port: 8888
---
spring:
  profiles: development

jdbc:
  url: jdbc:mysql://localhost:3306/test
  username: root1
  password: root1

---
spring:
  profiles: production

jdbc:
  url: jdbc:mysql://192.1.20.10:3306/shop
  username: root2
  password: root2